POST http://localhost:3000/users
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiam9uQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI3NzEwODExLCJleHAiOjE3Mjc3MTQ0MTEsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.t9KKS7TysMLxM4Gwmh0gcbGqv7vJ9O-vrr0XjM7ovwI

{
    "firstName": "Jon",
    "lastName": "Doe",
    "email": "favourejim56@gmail.com",
    "password": "#Johndoe1"
}
 


POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjgsImVtYWlsIjoiam9uQGV4YW1wbGUuY29tIiwiaWF0IjoxNzI3NzAxMjIyLCJleHAiOjE3Mjc3MDQ4MjIsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ._dLekBy_PIWoYuMHjYdsYac_cVqEcP7kCn1Tkqn67Gs


{
   "users" : [
{
    "firstName": "Mark",
    "lastName": "Doe",
    "email": "mark@example.com",
    "password": "#Johndoe1"
},
{
    "firstName": "tom",
    "lastName": "Doe",
    "email": "tom@example.com",
    "password": "#Johndoe1"
}
]
}